# Generate CjkChars.java containing GB2312 symbols + level-1 hanzi as \uXXXX escapes (ASCII-only source).
# Run once at dev time: powershell -File tools\gen-cjk-chars.ps1
$ErrorActionPreference = 'Stop'
$enc = [System.Text.Encoding]::GetEncoding('GB2312')
$sb = New-Object System.Text.StringBuilder
for ($hi = 0xA1; $hi -le 0xD7; $hi++) {
    for ($lo = 0xA1; $lo -le 0xFE; $lo++) {
        $ch = $enc.GetString([byte[]]@([byte]$hi, [byte]$lo))
        if ($ch.Length -eq 1 -and $ch[0] -ne [char]0xFFFD) {
            [void]$sb.Append($ch)
        }
    }
}
$chars = $sb.ToString()
Write-Host ('collected chars: ' + $chars.Length)

$esc = New-Object System.Text.StringBuilder
foreach ($c in $chars.ToCharArray()) {
    [void]$esc.Append('\u' + ('{0:x4}' -f [int]$c))
}

$out = 'D:\Dev\projects\CaveDream\core\src\main\java\com\cavedream\core\screen\CjkChars.java'

# Build the whole source in a StringBuilder and write via .NET directly (no PS pipeline quirks).
$doc = New-Object System.Text.StringBuilder
[void]$doc.Append('package com.cavedream.core.screen;')
[void]$doc.AppendLine()
[void]$doc.AppendLine('/**')
[void]$doc.AppendLine(' * GB2312 symbol area + level-1 hanzi full set, ' + $chars.Length + ' chars.')
[void]$doc.AppendLine(' * Generated by tools/gen-cjk-chars.ps1 - do not edit by hand.')
[void]$doc.AppendLine(' * Stored as double-backslash-uXXXX escapes so the source stays pure ASCII.')
[void]$doc.AppendLine(' */')
[void]$doc.AppendLine('public final class CjkChars {')
[void]$doc.AppendLine()
[void]$doc.AppendLine('    public static final String GB2312_L1 =')
[void]$doc.Append('            "')
[void]$doc.Append($esc.ToString())
[void]$doc.AppendLine('";')
[void]$doc.AppendLine()
[void]$doc.AppendLine('    private CjkChars() {')
[void]$doc.AppendLine('    }')
[void]$doc.AppendLine('}')
[System.IO.File]::WriteAllText($out, $doc.ToString(), [System.Text.Encoding]::ASCII)
Write-Host ('written: ' + $out)
